---
- name: ensure supporting SASL packages are installed
  yum:
    name: "{{ item }}"
    state: latest
  when: ansible_pkg_mgr == "yum"
  with_items:
    - cyrus-sasl
    - cyrus-sasl-lib
    - cyrus-sasl-plain

- name: ensure postfix is at the latest version
  package:
    pkg: postfix
    state: latest
    update_cache: yes
  notify:
    - restart postfix
  tags:
    - postfix
    - installation

- name: generate postfix main configuration
  template:
    dest=/etc/postfix/main.cf
    src=main.cf.j2
    owner=root
    group=root
    mode=0644
  notify:
    - restart postfix
  tags:
    - postfix
    - configuration

- name: generate postfix master configuration
  template:
    dest=/etc/postfix/master.cf
    src=master.cf.j2
    owner=root
    group=root
    mode=0644
  notify:
    - restart postfix
  tags:
    - postfix
    - configuration

- name: generate postfix password configuration
  template:
    dest: "/etc/postfix/sasl_passwd"
    src: sasl_passwd.j2
    owner: root
    group: root
    mode: 0600
  register: sasl_passwd_postmap
  notify:
    - restart postfix
  tags:
    - postfix
    - configuration

- name: ensure sasl_passwd is postmap
  shell: postmap /etc/postfix/sasl_passwd
  when: sasl_passwd_postmap|changed
  register: sasl_passwd_db
  notify:
    - restart postfix
  tags:
    - postfix
    - configuration

- name: ensure sasl_passwd.db as correct permissions
  file:
    path: /etc/postfix/sasl_passwd.db
    owner: root
    group: root
    mode: 0600
  when: sasl_passwd_db|changed
  notify:
    - restart postfix
  tags:
    - postfix
    - configuration

- name: enable postfix to start
  service:
    name: postfix
    state: started
    enabled: true
  tags:
    - postfix
    - service

# to test with ssh cli session on server:
# echo "Test mail from postfix" | mail -s "Local Outbound SMTP Test" matthew@newedgeengineering.com
